### PR TITLE
Fix closing of unopened span and div tags.

### PR DESCRIPTION
**Pull request by rikniitt**

### CODE REVIEW

**Comment by Nikschavan** [comment]
Thank you for the PR @rikniitt :)

Can you open an [issue](https://github.com/brainstormforce/all-in-one-schemaorg-rich-snippets/issues/new) for this first with what some description on how to reproduce this problem?

**Comment by rikniitt** [comment]
Thank you for quick response.

I opened new [issue](https://github.com/brainstormforce/all-in-one-schemaorg-rich-snippets/issues/18) describing how to reproduce the problem.

**Comment by sandeshjangam** [comment]
Hey @rikniitt thanks for PR request. I had reviewed the PR. Actually all given field of address is necessary to pass google testing tool. 
Actually fixed for this is Address should not show when street address is empty. Now we had changed the HTML of address accordingly and fixed this in 'dev' branch.

Please have look at 'dev' branch. If you still have any issue. Let us know.

**Comment by rikniitt** [comment]
Hey @sandeshjangam. Thanks for fixing the issue. I will close the pull request and wait for the plugin update.

**Pull request closed without merging**
